### ISSUE TITLE
SunXP should use Start logo from Explorer's resources

### ISSUE THREAD

**Issue by archeYR** [sagudev/SunXP#10]
Windows Luna theme uses a Start logo bitmap from Explorer's resources, if SunXP is meant to be a Luna clone, it should do the same IMO. Currently SunXP has a Start button and Start logo fused in one bitmap.

**Comment by sagudev** [comment]
The most important thing is to be compatible with ROS  and we have not have all icons, but I will check. Thanks. I'm impressed that you knows such detail. Maybe you can help us too. PRs are wellcome.

**Comment by archeYR** [comment]
It should work on ReactOS without any issues, here's how the Luna Start button looks on ReactOS.
![przechwytywanie](https://user-images.githubusercontent.com/32551254/40740736-eb684830-6449-11e8-80c2-eadde9e3b9bd.PNG)

Sure, I'm not a graphics designer, but will help as much as possible.

**Comment by sagudev** [comment]
Themes are made from two parts:
- graphic part (icons)
- text part (rc and ini files)
You can help us text part

**Comment by archeYR** [comment]
I've just done that, also removed the Start logo from the Start button bitmap, will make a PR soon.
![przechwytywanie](https://user-images.githubusercontent.com/32551254/40803049-c56b2ca0-6517-11e8-973b-3f682f3d19d3.PNG)

**Comment by sagudev** [comment]
Fixed in #11
