### ISSUE TITLE
[Bitmaps] Don't make svg or png

### ISSUE THREAD

**Issue by cernodile** [sagudev/SunXP#14]
We shouldn't make svgs or pngs as it overcomplicates the process, we do not need to scale. Bitmaps would be more flexible to pixel artists, as not everyone is that great at vectors. It makes no sense to overcomplicate the process. Direct bitmap would give us pixel by pixel perfection and craft for each asset.

**Comment by sagudev** [comment]
It would be good to make svg files but it is not necessary.

**Comment by cernodile** [comment]
@sagudev Why would it be good? It offers no benefit whatsoever for the style, it's just a overcomplication for those who are somewhat decent in just bitmap art. Not everyone can provide such accuracy in vectors.

**Comment by sagudev** [comment]
@katahiromz What do you think?
@cernodile Look at #2. BMPs are made from more icons, and every icon has special entry that defines icon. I am afraid that making BMP's in MSpaint will not give special entry that defines icon for each icon

**Comment by cernodile** [comment]
@sagudev I used lautus as base, it had icons defined like that.

**Comment by sagudev** [comment]
@cernodile But close button is bigger in windows xp then in Lautus so icon entrys will be wrong if use diferent size of icons and in SunXP case most icons are bigger than Lautus icons. Why they need to be bigger? Because Windows XP has bigger icons then Lautus.

**Comment by katahiromz** [comment]
https://graphicdesign.stackexchange.com/questions/63403/snap-to-grid-in-inkscape

**Comment by cernodile** [comment]
@katahiromz the point is we don't need vector at all for the theme. It'd be way less work if we did just bitmaps. Bitmaps would give us pixel by pixel accuracy.

**Comment by cernodile** [comment]
@sagudev I haven't changed any INI files, because taskbar is already the perfect size for this.

**Comment by sagudev** [comment]
@cernodile I am not talking about size in ini file but size of icons in bmp.

**Comment by katahiromz** [comment]
ok even if bmp only.

**Comment by cernodile** [comment]
@sagudev INI is used to redefine sizes of bmp with proper paddings.

**Comment by sagudev** [comment]
@cernodile Task bar is in perfect size but title bar or close button is bigger in Windows XP than in lautus

**Comment by archeYR** [comment]
@sagudev Actually, taskbar is a bit thicker in Luna theme.

**Comment by sagudev** [comment]
@archeYR can you open new issue and maybe PR.

**Comment by archeYR** [comment]
@sagudev I will fix that at some point.

**Comment by archeYR** [comment]
I think we've decided that only bmp files will be committed, is there any reason to keep this open?

**Comment by sagudev** [comment]
Ok, so now is not necessary to add svg files, but let's keep old svg files for at least one month.
