### ISSUE TITLE
About the ini files...

### ISSUE THREAD

**Issue by archeYR** [sagudev/SunXP#17]
We have to decide what to do with the ini files, that are responsible for theme's appearance. We can legally use the ini files from the Luna theme, these files also include the comments that are explaining what the given setting or value does. So, the options are following...

1. Copy the content from Luna ini files and prepare it to use with SunXP theme.
2. Same as above, but without comments (just like in SunXP in its current state/Lautus).
3. Change the vaules related only to the given bitmap when committing that bitmap.
4. Any other idea...?

**Comment by sagudev** [comment]
Are you sure that we can use ini files from luna theme? Can you get evidences?

**Comment by archeYR** [comment]
One of the ReactOS developers said "Discussing the legality of these .msstyles files is of limited use. A .msstyles file will not be included in the ROS source tree either way – instead this file must be created during our build process from the individual images and text files, as done for Lautus: https://github.com/reactos/reactos/tree/master/media/themes/lautus.msstyles
So if someone wanted to de-compose the Plastic theme and bring it into this form, that would reduce our problem to: (a) the legality of the individual images (i.e. they must all have been created from scratch and not modified or copied from MS's version), (b) the theme's license (must be GPL-compatible, e.g. CC-BY).
Given that the theme as distributed is clearly based on MS's version, (a) must be validated carefully and should likely be proven beyond reasonable doubt – so it may be more sensible to create a new theme from scratch with traceable origins instead." - this means that we can redistribute theme with Luna configuration, as it's built with our own build process.

**Comment by sagudev** [comment]
I'm allready extracted plastic theme and build it with rosbe. Can you ask one of ROS "leaders" if is realy legaly? I do not want to do something for nothing.

**Comment by archeYR** [comment]
Ok, I've asked them, we won't use ini files directly extracted from the Luna theme to make sure that we are legal, we will use only the vaules that are required to make it looking like Luna, actually, Lautus theme already has many values that are same as in Luna, so we can share some vaules, the thing is that the file shouldn't be the same. I think that the option 3 is most viable then, anyone has some other ideas?

**Comment by sagudev** [comment]
We can use luna theme for example to know how to write SunXP. And use Copy&Paste.

**Comment by archeYR** [comment]
When someone commits a bitmap, I (or anyone else may do that) will commit the ini changes related to that bitmap, I think it's the best way. I don't want to change everything at once.

**Comment by sagudev** [comment]
Ok

**Comment by sagudev** [comment]
I'm closing this issue in favor of #18 
But we will still need you.
