### ISSUE TITLE
[Bitmaps] Initial icons

### ISSUE THREAD

**Issue by sagudev** [sagudev/SunXP#2]
We need icons in bmp format.

**Comment by cernodile** [comment]
By icons; do you mean ones like folders, or the bitmaps for actual UI?

**Comment by sagudev** [comment]
ReactOS does not support icons for folders and programs so i mean the bitmaps for actual UI.
#3

**Comment by sagudev** [comment]
@katahiromz For icons we need Bitmaps (.BMP). Although vector images are great as you can get any resolution, we need bmp icons for end product. BMP can have multiple icons in one file (look at lautus startmenu bmp)

**Comment by katahiromz** [comment]
OK. We should check constants in <vsstyle.h> and lay the bitmap images.
https://msdn.microsoft.com/ja-jp/library/windows/desktop/bb773210.aspx

**Comment by sagudev** [comment]
https://github.com/reactos/reactos/blob/c2c66aff7dacc62d125f2cd61d1167e9a2aa3fd6/sdk/include/psdk/vsstyle.h

**Comment by sagudev** [comment]
![slika](https://user-images.githubusercontent.com/16504129/40671706-f2f689dc-636c-11e8-8245-f3ec7563bdb9.png)

https://www.codeproject.com/Articles/6171/Access-multiple-icons-in-a-single-icon-file?msg=5109050

**Comment by sagudev** [comment]
https://translate.googleusercontent.com/translate_c?act=url&depth=1&hl=sl&ie=UTF8&prev=_t&rurl=translate.google.com&sl=auto&sp=nmt4&tl=en&u=https://www.deskmodder.de/wiki/index.php/Vista_msstyle:_Die_Aufschl%25C3%25BCsselung&xid=17259,1500001,15700002,15700021,15700124,15700149,15700168,15700173,15700186,15700191,15700201,15700205&usg=ALkJrhg6OdYKhsgW7i828ZN_jWWOT-Sbpg

**Comment by sagudev** [comment]
For example NORMAL_STARTBUTTON.bmp has 3 images and imagecount = 3 first image is 0x0 - 25x43 second is 25x43 - 50x43

**Comment by sagudev** [comment]
https://knowledge.autodesk.com/search-result/caas/CloudHelp/cloudhelp/2015/ENU/MAXScript-Help/files/GUID-E5EE5B39-C8F2-4AB5-A890-C39C5EFB39E5-htm.html

**Comment by sagudev** [comment]
https://en.wikipedia.org/wiki/ICO_(file_format)#Icon_resource_structure

**Comment by katahiromz** [comment]
For information:
http://katahiromz.web.fc2.com/iconmake/iconmaks.zip

**Comment by katahiromz** [comment]
There're many freeware tools to combine bmp and make ico.

**Comment by sagudev** [comment]
As you can see in https://github.com/sagudev/SunXP/blob/master/bitmaps/NORMAL_BALLOONCLOSE.bmp there are 3 icons:

1. Button
2. Button on hover
3. button on click

![slika](https://user-images.githubusercontent.com/16504129/40675682-b24ac02c-6378-11e8-800a-b72209271980.png)
Can you make this from svg. The final file needs to have name: NORMAL_BALLOONCLOSE.bmp so BMP file. And if BMP works we will continue with current Design Concept.

**Comment by katahiromz** [comment]
Done in #6.

**Comment by sagudev** [comment]
From now, please push new icons to sagudev/SunXP:icons_test

**Comment by sagudev** [comment]
![slika](https://user-images.githubusercontent.com/16504129/40727580-73f9c088-6428-11e8-8df0-855dcf69dcae.png)
It looks like we have help from inkscape: windows xp icons colors in one place

**Comment by sagudev** [comment]
I'm closing this issue in favor of #18
